### ISSUE TITLE
Instructions incomplete

### ISSUE THREAD

**Issue by jcollum** [M2Team/NSudo#13]
The readme doesn't say how I *get* `nsudo`. I cloned the repo -- do I have to compile it? I can't find any exe file in the cloned files or instructions about where to get the exe.

**Comment by MouriNaruto** [comment]
![1](https://user-images.githubusercontent.com/10867563/37813103-9f468b96-2e9e-11e8-9729-e6eb2c12434d.png)
You can get NSudo to click this when you read the ReadMe.md in the GitHub.
Or you can download NSudo at https://github.com/M2Team/NSudo/releases/latest

I hope I can help you.

Mouri
