### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by wwtex** [M2Team/NSudo#14]
Have you considered putting NSudo on a Windows package repository like [Chocolatey](https://chocolatey.org/) or [scoop](https://scoop.sh/)? Being a system administration tool, there would be a lot of benefit from having it hosted there.

**Comment by MouriNaruto** [comment]
@wwtex Thank you for your suggestion. I had never considered before. But I will follow your suggestion after trying to use Chocolatey and scoop.

**Comment by MouriNaruto** [comment]
> How about nuget?

NSudo is not a .Net library, so I don't know is it suitable?

**Comment by MouriNaruto** [comment]
@wwtex Someone had added the NSudo to Chocolatey (https://chocolatey.org/packages/nsudo) and scoop (https://github.com/lukesampson/scoop/issues/3144). I wonder to show my thanks.

I will add the install method for these package managers after I have used them.

**Comment by MouriNaruto** [comment]
Closed because Chocolatey and scoop are supported now, and provide the usage in the documents.
