### ISSUE TITLE
NSudoC

### ISSUE THREAD

**Issue by optomux** [M2Team/NSudo#21]
Why NSudoC show window if you launch without parameters?! Is there way to hide window?

**Comment by MouriNaruto** [comment]
Please use NSudoG

**Comment by optomux** [comment]
That shows a GUI window? There used to be a NSudoC version with no windows at all.

**Comment by MouriNaruto** [comment]
NSudoC.exe = NSudo Windows Console Subsystem Version (Command Line Only)
NSudoG.exe = NSudo Windows Subsystem Version (Command Line Only)
NSudo.exe = NSudo Windows Subsystem Version (Command Line and Graphic User Interface for newbie)

The command line usage of all executables are the same. 

If you want to use command line version and don't want to pop up a black window, please use NSudoG.exe or NSudo.exe.

Mouri.
