### ISSUE TITLE
"Failed to create a process." ”进程创建失败“

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NSudo#25]
![1](https://user-images.githubusercontent.com/10867563/59965961-cad9d180-9547-11e9-8cb7-2be9009c1ec9.png)
![image](https://user-images.githubusercontent.com/10867563/59965990-391e9400-9548-11e9-956a-4e2a051c1e53.png)

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/59966061-25bff880-9549-11e9-8135-96965d096dba.png)

Windows 10, version 1903

**Comment by lkk440502** [comment]
我使用GenP 2.4在WIN 10 1909的版本上，發生的的情形跟MouriNaruto 一樣，改用GenP 2.2問題就解決了！

**Comment by MouriNaruto** [comment]
@lkk440502 然而 GenP 不是我的作品，却因为其弹 NSudo 的对话框以至于作为 NSudo 作者的我收到了不少邮件（

**Comment by color-space** [comment]
same problem

**Comment by color-space** [comment]
fixed with newer version i think

**Comment by rugabunda** [comment]
Same issue, windows 10 2004

**Comment by MouriNaruto** [comment]
The issue is opened too long. I don't know the issue whether I solved or not. So I closed this issue. Please fire a new issue if you still met the issue.

**Comment by celphogeek** [comment]
Make sure that you have Windows Modules Installer service running, I disable this service and I had this problem.
