### ISSUE TITLE
NSudo快捷命令配置文件命令行不能有空格

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NSudo#3]
反馈者：老八

**Comment by fcharlie** [comment]
你如果解析的 ini 格式文件，字符串可以用 `"path/to /file"` 这样的格式，这个是支持空格的

**Comment by ohyooo** [comment]
我的解决方法是再加一层引号，NSudo.json 里变成：
`"task":"\"F:\\Program Files\\Process Hacker\\ProcessHacker.exe\""`

ShortCutList.ini 里也差不多：
`""F:\Program Files\Process Hacker\ProcessHacker.exe""`

**Comment by MouriNaruto** [comment]
Moved to Projects Board

**Comment by MouriNaruto** [comment]
这不是Bug，请按照JSON配置规范为命令行添加引号
