### ISSUE TITLE
Appveyor Build Failures

### ISSUE THREAD

**Issue by bfoos** [M2Team/NSudo#31]
You may want to look into your appveyor configuration as CI Build's 375 through current (392 as of this comment) have failed.

**Comment by MouriNaruto** [comment]
It's a known issue because that I have introduced some .Net Core projects for developers who want to integrate the NSudo in their apps.

But I will fix the issue ASAP.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Fixed. Thanks.

https://ci.appveyor.com/project/MouriNaruto/nsudo/builds/29306370

Kenji Mouri
