### ISSUE TITLE
Crash when there is a tab in the commandline

### ISSUE THREAD

**Issue by cw2k** [M2Team/NSudo#38]
I use NSudo in a AutoItscript I noticed that I run NSudo like this:
`"Resources\helper\NSudo.exe -U:T" & @TAB & "%windir%\notepad.exe"`
I'll crash.
When I replace the '@TAB' with a space - it works:
`"Resources\helper\NSudo.exe -U:T" & " " & "%windir%\notepad.exe"`

However @TAB and Space should be in the same class of whitespace and both work.
I guess the commandlineparser needs some fixing here.

**Comment by MouriNaruto** [comment]
Thanks for your feedback. I will check it.

**Comment by MouriNaruto** [comment]
The issue is opened too long. I don't know the issue whether I solved or not. So I closed this issue. Please fire a new issue if you still met the issue.
