### ISSUE TITLE
NSudo_8.0_All_Components.zipFailed - Virus detected

### ISSUE THREAD

**Issue by bramson** [M2Team/NSudo#40]
Cannot download zip from any source because WIndows detects a virus.

**Comment by MouriNaruto** [comment]
I don't know how to feedback to Windows Defender to solve the misdetection issue.

I think I should use the digital signature to solve the issue. But I need some money to buy it.
So, someone can sponsor me via Patreon and afdian.

**Comment by MouriNaruto** [comment]
I have report to the Windows Defender and solve the issue.
