### ISSUE TITLE
大神如果用C#怎么引用您的dll啊

### ISSUE THREAD

**Issue by cagedh1** [M2Team/NSudo#46]

**Comment by MouriNaruto** [comment]
可参阅 src\MSIL\M2.NSudo

**Comment by cagedh1** [comment]
最新稳定版的二进制是哪个，能给个图或者链接吗，谢谢大佬了

**Comment by MouriNaruto** [comment]
这是一个标准的存放在 GitHub 上的项目，自己去 GitHub Releases 里面或者去官网找

**Comment by cagedh1** [comment]
好的 大神 能留个联系方式么 想咨询一些问题 可以有偿

**Comment by MouriNaruto** [comment]
联系方式可以查看我的 GitHub 首页，有邮件地址
