### ISSUE TITLE
Comodo False Positive

### ISSUE THREAD

**Issue by abdullah-erturk** [M2Team/NSudo#49]
Comodo Client Security is used in the institution where I work.

I am sure there is no malware in this project, but unfortunately Comodo sees (Win32) NSudoLG.exe and NSudoLC.exe files as infected (MalCrypt.Indus!@1qrzi1).

Therefore I can not use.

**Comment by MouriNaruto** [comment]
I guess it may the issue from VC-LTL toolchain which used to compile project NSudo.

**Comment by MouriNaruto** [comment]
I think you can submit the NSudo binaries to Comodo for removing false positives.
