### ISSUE TITLE
ShortcutList no longer accept multi "quotation marks" 

### ISSUE THREAD

**Issue by fuba82** [M2Team/NSudo#51]
Hi there,
the Shortcut List in v6.2.1812.31 accepted multi "quotation marks" like this:
```
"Hosts (Notepad++)": "\"%ProgramFiles%\\Notepad++\\notepad++.exe\" -multiInst -nosession \"%windir%\\System32\\Drivers\\etc\\hosts\"",
```  

but in v8.0 Update 1 this no longer works!  
seems the new version can not handle SPACES in the Shortcut List because also
```
"Notepad++": "%ProgramFiles%\\Notepad++\\notepad++.exe",
```
and 
```
"TEST": "C:\\Program Files\\Notepad++\\notepad++.exe",
```
does not work!

BUT
```
"TEST": "C:\\PROGRA~1\\Notepad++\\notepad++.exe -multiInst -nosession %windir%\\System32\\Drivers\\etc\\hosts",
```
does work but if there would be SCPASEC anywhere, it would not work again :/

maybe you can fix this?

Thanks

**Comment by MouriNaruto** [comment]
I will try to fix it if I can find it.

**Comment by MouriNaruto** [comment]
The issue is opened too long. I don't know the issue whether I solved or not. So I closed this issue. Please fire a new issue if you still met the issue.
