### ISSUE TITLE
NSudo在每次系统重启后无法运行

### ISSUE THREAD

**Issue by i35010u** [M2Team/NSudo#55]
每次下载后正常运行，重启后无法运行，请问这是NSudo自身的bug还是NSudo被火绒或WD误杀了？

**Comment by MouriNaruto** [comment]
请提供详细一些的信息

**Comment by i35010u** [comment]
> 请提供详细一些的信息

打开后提示uac，同意uac后短暂弹出控制台界面，随后很快消失，任务管理器中无nsudo相关进程

**Comment by MouriNaruto** [comment]
能否提供你用的 NSudo 二进制，毕竟我这里暂时没有问题

**Comment by MouriNaruto** [comment]
The issue is opened too long. I don't know the issue whether I solved or not. So I closed this issue. Please fire a new issue if you still met the issue.
