### ISSUE TITLE
English Gui?

### ISSUE THREAD

**Issue by rlesch** [M2Team/NSudo#56]
I see screenshots on the web of the Gui in english, but running the latest versuin seems to be only in chinese, with no option to change language?

**Comment by MouriNaruto** [comment]
NSudo will follow the language settings from Windows.

**Comment by rlesch** [comment]
hm, that doesnt seem to work here.. Does it switch to chinese as default if the system is running an unsupported language setting? if thats the case mho english as default would be wiser.

**Comment by MouriNaruto** [comment]
> Does it switch to chinese as default if the system is running an unsupported language setting?
No, NSudo should use English when running under an unsupported language setting, and it should be decided by Windows itself.

What's your language used in Windows?

**Comment by MouriNaruto** [comment]
I have tested on Windows 10, Version 1809 with Japanese and find the same issue. I will try to fix it.

**Comment by MouriNaruto** [comment]
> Does it switch to chinese as default if the system is running an unsupported language setting?

@rlesch It seems it will use chinese when the system is running an unsupported language.

**Comment by MouriNaruto** [comment]
@rlesch Maybe the issue had been fixed. (Reference: https://github.com/M2Team/NSudo/commit/68ff11c909943ef241216f36c38b10de36d29cb4)

**Comment by rlesch** [comment]
Thank you!
