### ISSUE TITLE
GitHubPage的一处问题

### ISSUE THREAD

**Issue by cyb233** [M2Team/NSudo#57]
GitHubPage页中
点击`相关人士 Relevant People`后语言会切换为English
Android 10，Chrome 88

**Comment by MouriNaruto** [comment]
这个属于已知问题……因为希望只更新一份人士清单

**Comment by MouriNaruto** [comment]
倒是这方面应该会改进一下的

**Comment by MouriNaruto** [comment]
已改善 https://github.com/M2Team/NSudo/commit/4a83264499674fae6aead198abf52876184c2d87
