### ISSUE TITLE
为什么miniFM没有了呢？

### ISSUE THREAD

**Issue by ysj19921026** [M2Team/NSudo#6]
为什么miniFM没有了呢？我下载了最新的4.4版本，发现没有miniFM了

**Comment by MouriNaruto** [comment]
MiniFM从NSudo 4.3.1703.8开始移除

当时认为MiniFM功能鸡肋，不如用第三方文件管理器

**Comment by MouriNaruto** [comment]
但是不排除增强后的MiniFM重新回归
