### ISSUE TITLE
windwos10 19043 21H1 某些计划任务任不能删除 

### ISSUE THREAD

**Issue by lkj00** [M2Team/NSudo#63]
删除windows10 19043 21H1 启用了所有权限  运行 taskschd.msc  删除计划任务的时候 某些任然提示没有权限！无法删除

![批注 2021-05-27 164650](https://user-images.githubusercontent.com/77599184/119795569-2e769180-bf0b-11eb-9f59-68e47124791e.png)

**Comment by MouriNaruto** [comment]
希望你能提供更详细的信息

**Comment by MouriNaruto** [comment]
The issue is opened too long. I don't know the issue whether I solved or not. So I closed this issue. Please fire a new issue if you still met the issue.
