### ISSUE TITLE
NSudo fails to execute any program when LSA Protection (RunAsPPL) in Lsass (Local Security Authority Process) is enabled

### ISSUE THREAD

**Issue by md500** [M2Team/NSudo#79]
If LSA Protection is enabled according to [Microsoft](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection#to-enable-lsa-protection-on-a-single-computer) or you [Enable Windows Defender Credential Guard by using the HVCI and Windows Defender Credential Guard hardware readiness tool](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#enable-virtualization-based-security-and-windows-defender-credential-guard) and you reboot the PC you cannot elevate privileges when this setting is enabled [unless the setting is removed](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection#to-disable-lsa-protection), disable Secure Boot (If has been enabled) and erase NVRAM settings (only if setting on efi variables is not removed).

...Or bypass RunAsPPL protection with Mimikatz:

![NSUDO WORKS IF PsProtectedSignerLsa-Light or PsProtectedSignerWinTcb is DISABLED](https://user-images.githubusercontent.com/3111925/132197712-ee40d44d-994f-40cb-bfe5-bc5b0322b41f.png)
![Nsudo Works!](https://user-images.githubusercontent.com/3111925/132198101-9510b1a8-0451-45bb-9352-1268143252ab.png)
[log.txt](https://github.com/M2Team/NSudo/files/7114975/log.txt)

This happens when PsProtectedSignerWinTcb (only enable with Mimikatz) or PsProtectedSignerLsa-Light protection on Lsass.exe is enabled when RunAsPPL registry key is enabled, or this setting is stored on Efi variables in NVRAM (efi variables of this settings only SecureBoot is enabled):

![RunAsPPL](https://user-images.githubusercontent.com/3111925/132196159-f5bfefa8-6c89-446c-8990-7abc0ff531e5.png)
[LogErrorPPL.txt](https://github.com/M2Team/NSudo/files/7114922/LogErrorPPL.txt)

![Nsudo Fail!](https://user-images.githubusercontent.com/3111925/132196476-6d91bf98-60a3-4023-9e5f-46016795b215.png)
[logError.txt](https://github.com/M2Team/NSudo/files/7114933/logError.txt)

However ExecTI works even any LSA Protection is enabled and no drivers... [Maybe this info?](https://blog.scrt.ch/2021/04/22/bypassing-lsa-protection-in-userland/) (Credits for itm4n)

![ExecTI works even lsass exe is protected with PsProtectedSignerWinTcb and PsProtectedSignerLsa-Light but Nsudo gives an error if any protection is enabled](https://user-images.githubusercontent.com/3111925/132199139-d72b5810-f7bd-4e3c-9ff9-d201e006ab21.png)

I find this temporary solution using [this page](https://itm4n.github.io/lsass-runasppl/) (thanks itm4n for this info) which explains what is PPL and how it works, and how RunAsPPL is bypassed using an signed kernel driver of Mimikatz.

Hope this information helps to make Nsudo run in an secure system!

**Comment by MouriNaruto** [comment]
I am really appreciate with you because you let me know that. It's really helpful for me.

Many people have reported me they meet the issue and I found the failed step is getting SYSTEM token, and I make a solution and they found the issue solved. You can try this new behavior in https://github.com/M2Team/NSudo/releases/tag/9.0-Preview1.

> NSudo will try to open the access token from lsass.exe for maximum privileges in the access token, and try to open the access token from winlogon.exe of current active session as fallback.

I will try to analyse the information you provided me and hope to improve the fallback solution of getting SYSTEM token.

Kenji Mouri

**Comment by MouriNaruto** [comment]
> However ExecTI works even any LSA Protection is enabled and no drivers...

I have analyse ExecTI and found it only open the access token from winlogon.exe of current active session.

![image](https://user-images.githubusercontent.com/10867563/132208519-2730a4c7-0dfd-40ee-9f82-89d749eed710.png)

Kenji Mouri

**Comment by MouriNaruto** [comment]
Closed issue because NSudo 9.0 Preview 1 fixed that.
