### ISSUE TITLE
Failed to create a process

### ISSUE THREAD

**Issue by Rrhyast** [M2Team/NSudo#82]
****************************************************************

Sender: NSudoCreateProcess
DateTime: 2021-10-07 06:18:52
Process ID: 15352
Thread ID: 6996

UserModeType: 1
PrivilegesModeType: 1
MandatoryLabelType: 0
ProcessPriorityClassType: 2
ShowWindowModeType: 0
WaitInterval: 0
CreateNewConsole: 1
CommandLine: "C:\Users\X\Desktop\Toolkit_11.8\ToolKit.cmd"
CurrentDirectory: C:\Users\X\Desktop\Toolkit_11.8\Bin\x64

****************************************************************

Sender: NSudoCreateProcess
DateTime: 2021-10-07 06:18:52
Process ID: 15352
Thread ID: 6996

Create process failed, returns -2147024894.

****************************************************************

**Comment by MouriNaruto** [comment]
I am suggesting you to try https://github.com/M2Team/NSudo/releases/tag/9.0-Preview1.

Kenji Mouri

**Comment by Syrin10** [comment]
I have this problem with all 8.x builds up to an including 8.2 while the older version I was using did fine.
I tracked it down to settings LSA to run as a protected process and rebooting the system

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa]
"RunAsPPL"=dword:00000001

I think I'll stick with the old version for now rather than run it as a normal process

**Comment by Thuan-1954** [comment]
Hi,

I'm a newbie and just started today.  I'm posting here to get help.  Trying v 9.0 Preview, or the most current version 8.2, or LSA setting tweak didn't help.  Please advise and help.  Thanks.

**Comment by scerazy** [comment]
Exactly the same issue:

`M2-Team NSudo Launcher 9.0 Preview 1 (Build 2676)
© M2-Team. All rights reserved.

Error: Failed to create a process.

For further information, please visit https://nsudo.m2team.org.

****************************************************************

Sender: NSudoCreateProcess
DateTime: 2022-10-05 15:26:00
Process ID: 10752
Thread ID: 10756

UserModeType: 2
PrivilegesModeType: 1
MandatoryLabelType: 0
ProcessPriorityClassType: 2
ShowWindowModeType: 2
WaitInterval: 0
CreateNewConsole: 1
CommandLine: cmd /c start "NSudo.Launcher" powershell
CurrentDirectory: C:\Windows

****************************************************************

Sender: NSudoCreateProcess
DateTime: 2022-10-05 15:26:00
Process ID: 10752
Thread ID: 10756

Create process failed, returns -2147024891.

****************************************************************
`
