### ISSUE TITLE
以获取System权限下如何提升到TrustedInstaller权限

### ISSUE THREAD

**Issue by mycreategit** [M2Team/NSudo#87]

**Comment by MouriNaruto** [comment]
请问你要表达什么？

**Comment by mycreategit** [comment]
已获取System权限，如何将权限提升至TrustedInstaller

**Comment by MouriNaruto** [comment]
直接用 NSudo 获取 TrustedInstaller 权限即可
如果是自己手工实现的话，则是启动 TrustedInstaller 服务根据返回的进程 ID 获取令牌，然后 CreateProcessAsUser
