### ISSUE TITLE
帮助信息里有个语病

### ISSUE THREAD

**Issue by qaqz111** [M2Team/NSudo#89]
-CurrentDirectory:[ 目录路径 ] 设置进程的的当前目录。
PS: 如果你想用 NSudo Launcher 的当前目录, 请不要包含 "-CurrentDirectory" 参数。

这一段第一行的两个“的”应该去掉一个。

bs强迫症了wkao /笑哭

**Comment by MouriNaruto** [comment]
了解，最近会抽空修复

毛利

**Comment by MouriNaruto** [comment]
已修复，遂关闭问题

https://github.com/M2Team/NSudo/commit/ea835ea13823e61c748ef89ed9eef59abefe446f

毛利
