### ISSUE TITLE
.Net Framework support for NSudo Shared Library

### ISSUE THREAD

**Issue by Cryolitia** [M2Team/NSudo#91]
I'm using .Net Framework 4.8 in order to build a mini tool without any runtime like .net 5, but i found that NSudo Shared Library won't worked with exception "未能加载文件或程序集“System.Runtime, Version=5.0.0.0"
Could u please publish NSudo Shared Library with .Net Standard 2.0 so that both .Net Framework and .Net Core could use the fansinating library.

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NSudo/commit/f63546600a9bbbe9d1350fa9111d085fd3feedc9

I have just added the .NET Framework support for NSudo Shared Library. Thanks.

Kenji Mouri

**Comment by laug3044** [comment]
كود البطاقة هو:  
 GJTN3-IW2FY-B2PPZ
